name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]
    branches: [release]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mc-rcon-discord

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Workflow
    permissions:
      contents: read
      packages: write
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate automatic version
      id: version
      run: |
        # Generate date-based version with build number
        DATE=$(date +'%Y.%m.%d')
        BUILD_NUMBER=${{ github.run_number }}
        SHORT_SHA=$(git rev-parse --short HEAD)
        
        # Create version string: YYYY.MM.DD.BUILD_NUMBER
        VERSION="${DATE}.${BUILD_NUMBER}"
        VERSION_WITH_SHA="${VERSION}-${SHORT_SHA}"
        
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "version_with_sha=${VERSION_WITH_SHA}" >> $GITHUB_OUTPUT
        echo "date=${DATE}" >> $GITHUB_OUTPUT
        echo "build_number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        
        echo "Generated version: ${VERSION}"
        echo "Generated version with SHA: ${VERSION_WITH_SHA}"

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=${{ steps.version.outputs.version_with_sha }}
          type=raw,value=${{ steps.version.outputs.date }}
          type=raw,value=latest
          type=ref,event=branch
          type=raw,value=build-${{ steps.version.outputs.build_number }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Docker Hub README
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: loafabreadly/mc-rcon-discord
        readme-filepath: ./README-DOCKERHUB.md